spring:
  application:
    name: astra-backend
server.port: 8081
astra:
  embedding:
    ollama:
      base-url: http://localhost:11434
      model: nomic-embed-text
  llm:
    base-url: http://localhost:11434
    model: qwen2.5:1.5b